alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "web"
    scrape_interval: 30s
    static_configs:
      - targets:
          - 127.0.0.1:8000

  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9090

  - job_name: "node"
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9100


  - job_name: "postgres"
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9187

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:8080
    basic_auth:
      username: admin
      password: admin

  - job_name: "promtail"
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:9080

  - job_name: "loki"
    scrape_interval: 30s
    static_configs:
      - targets:
          - localhost:3100
