# Generated by Django 5.1.5 on 2025-01-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_incoming_game"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="steam",
            new_name="steam_game",
        ),
    ]
