# Generated by Django 5.1.5 on 2025-01-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_auto_20250122_2314"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PriceRules",
            new_name="PriceRule",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="concurrent",
            options={"verbose_name": "Конкурент", "verbose_name_plural": "Конкуренты"},
        ),
        migrations.AlterModelOptions(
            name="concurrentprice",
            options={
                "verbose_name": "Цена конкурента",
                "verbose_name_plural": "Цены конкурентов",
            },
        ),
        migrations.AlterModelOptions(
            name="developer",
            options={
                "verbose_name": "Разработчик",
                "verbose_name_plural": "Разработчики",
            },
        ),
        migrations.AlterModelOptions(
            name="distributor",
            options={
                "verbose_name": "Дистрибьютор",
                "verbose_name_plural": "Дистрибьюторы",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={
                "verbose_name": "Игра на сайте",
                "verbose_name_plural": "Игры на сайте",
            },
        ),
        migrations.AlterModelOptions(
            name="gameimage",
            options={"verbose_name": "Фото игры", "verbose_name_plural": "Фото игр"},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"verbose_name": "Жанр", "verbose_name_plural": "Жанры"},
        ),
        migrations.AlterModelOptions(
            name="incoming",
            options={
                "verbose_name": "Поступление",
                "verbose_name_plural": "Поступления",
            },
        ),
        migrations.AlterModelOptions(
            name="key",
            options={"verbose_name": "Ключ", "verbose_name_plural": "Ключи"},
        ),
        migrations.AlterModelOptions(
            name="pricerule",
            options={"verbose_name": "Правило", "verbose_name_plural": "Правила"},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"verbose_name": "Издатель", "verbose_name_plural": "Издатели"},
        ),
        migrations.AlterModelOptions(
            name="steamgame",
            options={
                "verbose_name": "Игра в Steam",
                "verbose_name_plural": "Игры в Steam",
            },
        ),
        migrations.AlterField(
            model_name="game",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(verbose_name="Дата релиза"),
        ),
        migrations.AlterField(
            model_name="game",
            name="requirements",
            field=models.TextField(verbose_name="Системные требования"),
        ),
        migrations.AlterField(
            model_name="incoming",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Дата отгрузки"),
        ),
    ]
