# Generated by Django 5.1.5 on 2025-01-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricerule",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="website.category"
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="developers",
            field=models.ManyToManyField(
                blank=True, related_name="developers", to="website.developer"
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="genres", to="website.genre"
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="publishers",
            field=models.ManyToManyField(
                blank=True, related_name="publishers", to="website.publisher"
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="release_date_lower",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата выхода меньше чем"
            ),
        ),
        migrations.AlterField(
            model_name="pricerule",
            name="steam_apps",
            field=models.ManyToManyField(
                blank=True,
                help_text="Steam Id игр, правило применяется ко всем играм, указанных здесь. Другие ограничения не учитываются",
                related_name="steam_apps",
                to="website.steamgame",
            ),
        ),
    ]
